# Generated by Django 5.0.1 on 2024-01-05 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("controllers", "0002_alter_controllerdevice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="controllerdevice",
            name="last_ping_timestamp",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="controllerdevice",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="controllerdevicestateevent",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
