# Generated by Django 5.0.1 on 2024-01-05 17:52

from django.conf import settings
from django.db import migrations, models


def migrate_controllers_m2m(apps, schema_editor):
    ControllerDevice = apps.get_model("controllers", "ControllerDevice")
    for controller in ControllerDevice.objects.all():
        if controller.user:
            controller.users.set([controller.user])
        controller.user = None
        controller.save()


class Migration(migrations.Migration):
    dependencies = [
        ("controllers", "0003_controllerdevice_last_ping_timestamp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="controllerdevice",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="controllerdevice",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="controllers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(
            migrate_controllers_m2m, reverse_code=migrations.RunPython.noop
        ),
    ]
