version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 0.0.0.0:1883:1883
      - 0.0.0.0:8883:8883
      - 0.0.0.0:9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/cert:/mosquitto/cert
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
  backend:
    build:
      context: backend/src
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./backend/src/db.sqlite3:/app/db.sqlite3
    ports:
      - "0.0.0.0:8000:8000"
    restart: unless-stopped
volumes:
  mosquitto_data:
  mosquitto_log:
