version: '3.8'

services:
    mosquitto:
        image: eclipse-mosquitto:2
        ports:
            - 0.0.0.0:1883:1883
            - 0.0.0.0:8883:8883
            - 0.0.0.0:9001:9001
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - mosquitto_data:/mosquitto/data
            - mosquitto_log:/mosquitto/log

volumes:
  mosquitto_data:
  mosquitto_log:
